name: 'Testcontainers Cloud'
description: 'Download and setup Testcontainers Cloud'
inputs:
  os:
    description: 'Operating system: linux | darwin | windows'
    required: true
    default: linux
runs:
  using: 'composite'
  steps:
    - id: validate-input
      shell: bash
      run: |
        [[ ${{ inputs.os }} =~ ^(linux|darwin|windows)$ ]] || { echo "Invalid OS parameter" ; exit 1; }
    - id: testcontainers-cloud
      shell: bash
      run: |
        # determine the architecture of the platform 
        suffix=$([[ $(uname -m) == "aarch64" || $(uname -m) == "arm64" ]] && echo "arm64" || echo "x86-64")
        
        # determine the extension of the package
        extension=$([[ ${{ inputs.os }} == "windows" ]] && echo ".exe")
        
        # fetch the latest TCC agent version and make it executable
        echo "Downloading https://app.testcontainers.cloud/download/testcontainers-cloud-agent_${{ inputs.os }}_$suffix$extension"
        curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_${{ inputs.os }}_$suffix$extension
        chmod +x agent
        
        # start agent as background process
        ./agent &
        
        # make sure TCC is ready before proceeding
        ./agent wait