name: 'Testcontainers Cloud'
description: 'Download and setup Testcontainers Cloud'
runs:
  using: 'composite'
  steps:
    - id: testcontainers-cloud
      shell: bash
      run: |
        # determine the architecture of the platform 
        suffix=$([[ $(uname -m) == "aarch64" || $(uname -m) == "arm64" ]] && echo "arm64" || echo "x86-64")
        
        # determine the os for the agent
        os=$([[ $RUNNER_OS == "macOS" ]] && echo "darwin" || echo $([[ $RUNNER_OS == "Windows" ]] && echo "windows" || echo "linux"))
        
        # determine the extension of the package
        extension=$([[ $os == "windows" ]] && echo ".exe" || echo "")

        # fetch the latest TCC agent version and make it executable
        echo "Downloading https://app.testcontainers.cloud/download/testcontainers-cloud-agent_${os}_${suffix}${extension}"
        curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_${os}_${suffix}${extension}
        chmod +x agent
        
        # start agent as background process
        ./agent &
        
        # make sure TCC is ready before proceeding
        ./agent wait